@startuml

title "Senders KYC flow"

actor User

User -> "Partner website": Register
"Partner website" -> User: Registered
"Partner website" -> Bitpesa: Create Bitpesa Sender
Bitpesa -> "Partner website": Sender ID
Bitpesa --> "Partner website": (Some time later) Sender Approved 
User -> "Partner website": Can transact using Bitpesa with Sender ID
@enduml
